// POST
export const GET_LIST_POST = 'GET_LIST_POST';
export const FETCH_DATA_POST = 'FETCH_DATA_POST';
export const GET_DETAIL_POST = 'GET_DETAIL_POST';



// CATEGORY
export  const GET_LIST_CATEGORY = 'GET_LIST_CATEGORY';
export  const FETCH_DATA_CAT = 'FETCH_DATA_CAT';


// LOAD
export  const SHOW_LOADING = 'SHOW_LOADING';
export  const HIDE_LOADING = 'HIDE_LOADING';